name: Automatic Semantic Versioning

on:  
  push:
    branches:
       - feature/automation
jobs:
  build:
    name: Automatic Semantic Versioning 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Automatic Semantic Versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          major_pattern: "major:"
          minor_pattern: "minor:"
          format: "v${major}.${minor}.${increment}"
          
      - name: Automatic Release Creating
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          draft: false
          prerelease: false
