name: Automatic Semantic Versioning

on:  
  push:
    branches:
       - feature/automation
jobs:
  build:
    name: Automatic Semantic Versioning 
    runs-on: ubuntu-latest
    steps:
      - name: Creation of Tags
      - uses: actions/checkout@v2
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Extracting Version
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          version: "${{ steps.previous_step.outputs.version }}"
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Automatic Semantic Versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_prefix: "v"
          major_pattern: "major:"
          minor_pattern: "minor:"
          patch_pattern: "fix"
          format: "v${major}.${minor}.${patch}"
