name: Creation of Release Version

on:  
#  pull_request:
#    branches:
#      - main
  push:
    branches:
       - feature/automation
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v${{ github.run_number }}.0.0
          release_name: Release Number v${{ github.run_number }}.0.0
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
