name: Create Release

on:  
  push:
    branches:
       - feature/automation

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Creating Automatic Semantic Version 1 
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v${{ github.run_number }}.0.0
          release_name: v${{ github.run_number }}.0.0
          body: |
            Release is automatically created in Github with the format v${{ github.run_number }}.0.0
          draft: false
          prerelease: false
