name: Creation of Release Version
on:
  pull_request:
    branches: [master]
    types:
      - closed

jobs:
  if_merged:
    name: Create Release  
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Taking Latest Release Tag number
        id: releaseVersion
        run: |
          owner="prashant-demo110"
          repo="Automatic_Semantic_Versioning"
          release_json=$(curl https://api.github.com/repos/$owner/$repo/releases)
          Release_tag=$(echo "$release_json" | jq -r '.[0].tag_name')
          echo "Release_tag: Latest Tag is : $Release_tag"
          echo ::set-output name=Release_tag::"$Release_tag"
          
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.releaseVersion.outputs.Release_tag }}
#          current-version: "$Release_tag"
          version-fragment: '${{github.event.head_comment.body}}'
          
      - name: Create release version
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          owner="prashant-demo110"
          repo="Automatic_Semantic_Versioning"
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/$owner/$repo/releases \
            -d '{"tag_name":"${{ steps.bump_version.outputs.next-version }}","target_commitish":"master","name":"${{ steps.bump_version.outputs.next-version }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
