name: Creation of Release Version
on:  
  push:
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Taking Latest Release Tag number
        id: releaseVersion
        run: |
          owner="prashant-demo110"
          repo="Automatic_Semantic_Versioning"
          release_json=$(curl https://api.github.com/repos/$owner/$repo/releases)
          Release_tag=$(echo "$release_json" | jq -r '.[0].tag_name')
          
          echo "Release_tag: Latest Tag is : $Release_tag"
          echo ::set-output name=Release_tag::"$Release_tag"
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Bumping and Creating tags
        id: anotherVersion
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          WITH_V: true
          WITH_V: false 
          
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
#          current-version: ${{ steps.anotherVersion.outputs.Another_Version }}
          current-version: '2.2.2'
          version-fragment: 'feature'
          
      - name: Do something with your bumped release version
        run: echo ${{ steps.bump_version.outputs.next-version }}
