name: Creation of Release Version

on:  
#  pull_request:
#    branches:
#      - main
  push:
    branches:
       - feature/automation
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        INITIAL_VERSION: 0.0.0
    - name: Creating Automatic Semantic Version 
      id: versioning
      uses: PaulHatch/semantic-version@v4.0.2
      with:
        branch: main
        tag_prefix: "v"
        major_pattern: "major:"
        minor_pattern: "minor:"
        patch_pattern: "fix:"
        format: "v${major}.${minor}.${patch}"        
