name: Creation of Release Version

on:  
#  pull_request:
#    branches:
#      - main
  push:
    branches: [feature/automation]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Increment version from repository's tags
      id: tages_versioning
      uses: georgeneto/tags-versioning@v1
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
    - name: Release Number Output
      run: |
        echo "App Version 1: ${{ steps.version.outputs.last }}"
        echo "App Version 2: ${{ steps.version.outputs.next }}"
