name: Increment tags
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: prashant-demo110
        WITH_V: true
        RELEASE_BRANCHES: master
        SOURCE: .
        DRY_RUN: true
        INITIAL_VERSION: 0.0.0
        TAG_CONTEXT: repo
        PRERELEASE_SUFFIX: prerelease
        VERBOSE: true
