name: Creation of Release Version

on:  
#  pull_request:
#    branches:
#      - main
  push:
    branches:
       - feature/automation
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: DB Release
        id: db-version
        uses: PaulHatch/semantic-version@v5.0.0-alpha2
        with:
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          tag_prefix: version
          change_path: "src/database"
          search_commit_body: true
      - name: Github Release
        run: |
          echo "DB Version: ${{steps.db-version.outputs.version}}"
          echo "DB Tag: ${{steps.db-version.outputs.version_tag}}"
          echo "DB Changed: ${{steps.db-version.outputs.changed}}"
