name: Creation of Release Version

on:  
#  pull_request:
#    branches:
#      - main
  push:
    branches: [feature/automation]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: prashant-demo110
