name: Creation of Release Version

on:  
#  pull_request:
#    branches:
#      - main
  push:
    branches:
       - feature/automation
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bump version
        uses: PaulHatch/semantic-version@v4.0.2
        id: tag_version_develop
        with:
          tag_prefix: "v"
          major_pattern: "major:"
          minor_pattern: "minor:"
          format: "${major}.${minor}.${patch}"
          namespace: develop
          change_path: "."
          short_tags: false
          bump_each_commit: true
