name: Creation of Release Version
on:  
  push:
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Taking Latest Release Tag number
        id: releaseVersion
        run: |
          owner="prashant-demo110"
          repo="Automatic_Semantic_Versioning"
          release_json=$(curl https://api.github.com/repos/$owner/$repo/releases)
          Release_tag=$(echo "$release_json" | jq -r '.[0].tag_name')
          echo "Release_tag: Latest Tag is : $Release_tag"
          echo ::set-output name=Release_tag::"$Release_tag"
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Bumping and Creating tags
        id: anotherVersion
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false 
          
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
#          current-version: ${{ steps.anotherVersion.outputs.Another_Version }}
          current-version: '2.2.2'
          version-fragment: 'major'
          
      - name: Do something with your bumped release version
        run: |
          # GitHub CLI api
          # https://cli.github.com/manual/gh_api

          gh api \
            env: \
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/$owner/$repo/releases \
            -f tag_name='v3.3.3'
           -f target_commitish='master'
           -f name='v3.3.3'
           -f body='Description of the release'
           -F draft=false
           -F prerelease=false
           -F generate_release_notes=false
