name: Creation of Release Version

on:  
#  pull_request:
#    branches:
#      - main
  push:
    branches:
       - feature/automation
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Creating Automatic Semantic Version 2 
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "major:"
          minor_pattern: "minor:"
#          patch_pattern: "fix:"
          format: "${major}.${minor}.${patch}"
